### ISSUE TITLE
group icons smaller then expected = blur

### ISSUE THREAD

**Issue by poltertec** [solus-project/evolve-sc#3]
Top icon is original 64px icon
![screenshot from 2015-04-21 22-45-30](https://cloud.githubusercontent.com/assets/8506580/7262282/92fdfe1a-e878-11e4-9819-17135ae718cf.png)

**Comment by poltertec** [comment]
Nvm my bad still had that size to index.theme

**Comment by ikeydoherty** [comment]
So.. I don't need to do anything? :D

**Comment by poltertec** [comment]
Correct :p

**Comment by ikeydoherty** [comment]
Aww. Deprived me of work :D
